 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_Cfg.h
 *
 * Description:  This file contains the Pre_Compile Configurations for Port
 * 				 Module.
 *
 * Author: Mina Atef
 *
 *******************************************************************************/
#ifndef PORT_CFG_H_
#define PORT_CFG_H_

/*
 * VENDOR ID		2020
 */
#define PORT_VENDOR_ID								(2020U)

/*
 * MODULE ID		124
 */
#define PORT_MODULE_ID								(124U)

/*
 * Instance ID		0
 */
#define PORT_INSTANCE_ID							(0U)

/*
 * MODULE Version	1.0.0
 */
#define PORT_CFG_SW_MAJOR_VERSION						(1U)
#define PORT_CFG_SW_MINOR_VERSION						(0U)
#define PORT_CFG_SW_PATCH_VERSION						(0U)

/*
 * AUTOSAR RELEASE	4.0.3
 */
#define PORT_CFG_AR_RELEASE_MAJOR_VERSION				(4U)
#define PORT_CFG_AR_RELEASE_MINOR_VERSION				(0U)
#define PORT_CFG_AR_RELEASE_PATCH_VERSION				(3U)

#include"Std_Types.h"
/* AUTOSAR Release checking between Std_Types and Port_Cfg Modules */
#if((PORT_CFG_AR_RELEASE_MAJOR_VERSION != STD_TYPES_AR_RELEASE_MAJOR_VERSION)\
 || (PORT_CFG_AR_RELEASE_MINOR_VERSION != STD_TYPES_AR_RELEASE_MINOR_VERSION)\
 || (PORT_CFG_AR_RELEASE_PATCH_VERSION != STD_TYPES_AR_RELEASE_PATCH_VERSION))
#error"The AR Version of STD_Types Is not Compatible With AR Version of Port_Cfg "
#endif


/* Inside the PortGeneral Container */

/* Pre_compile option for Development Error Detect */
#define PORT_DEV_ERROR_DETECT				(STD_ON)
/* Pre_compile option for presence of Port_SetPinDirection API */
#define PORT_SET_PIN_DIRECTION_API			(STD_ON)
/* Pre_compile option for presence of Port_SetPinMode API */
#define PORT_SET_PIN_MODE_API				(STD_ON)
/* Pre_compile option for presence of Port_GetVersionInfo API */
#define PORT_VERSION_INFO_API				(STD_ON)


/* Inside the PortConfigSet */

/* The number of specified PortPins */
#define PORT_NUMBER_OF_PORT_PINS			(uint16)32



/* Port pins direction */
/* PORTA_REG PINS */
#define PORT_PIN00_ID						((uint16)0)
#define PORT_PIN01_ID						((uint16)1)
#define PORT_PIN02_ID						((uint16)2)
#define PORT_PIN03_ID						((uint16)3)
#define PORT_PIN04_ID						((uint16)4)
#define PORT_PIN05_ID						((uint16)5)
#define PORT_PIN06_ID						((uint16)6)
#define PORT_PIN07_ID						((uint16)7)
/* PORTB_REG PINS */
#define PORT_PIN08_ID						((uint16)8)
#define PORT_PIN09_ID						((uint16)9)
#define PORT_PIN10_ID						((uint16)10)
#define PORT_PIN11_ID						((uint16)11)
#define PORT_PIN12_ID						((uint16)12)
#define PORT_PIN13_ID						((uint16)13)
#define PORT_PIN14_ID						((uint16)14)
#define PORT_PIN15_ID						((uint16)15)
/* PORTC_REG PINS */
#define PORT_PIN16_ID						((uint16)16)
#define PORT_PIN17_ID						((uint16)17)
#define PORT_PIN18_ID						((uint16)18)
#define PORT_PIN19_ID						((uint16)19)
#define PORT_PIN20_ID						((uint16)20)
#define PORT_LED00_ID				    	((uint16)21)
#define PORT_PIN22_ID						((uint16)22)
#define PORT_PIN23_ID						((uint16)23)
/* PORTD_REG PINS */
#define PORT_PIN24_ID						((uint16)24)
#define PORT_PIN25_ID						((uint16)25)
#define PORT_BUTTON00_ID			 		((uint16)26)
#define PORT_PIN27_ID						((uint16)27)
#define PORT_PIN28_ID						((uint16)28)
#define PORT_PIN29_ID						((uint16)29)
#define PORT_PIN30_ID						((uint16)30)
#define PORT_PIN31_ID						((uint16)31)

/* Port Pins Direction */
#define PORT_PIN00_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN01_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN02_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN03_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN04_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN05_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN06_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN07_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN08_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN09_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN10_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN11_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN12_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN13_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN14_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN15_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN16_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN17_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN18_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN19_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN20_DIRECTION				(PORT_PIN_IN)
#define PORT_LED00_DIRECTION			    (PORT_PIN_OUT)
#define PORT_PIN22_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN23_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN24_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN25_DIRECTION				(PORT_PIN_IN)
#define PORT_BUTTON00_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN27_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN28_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN29_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN30_DIRECTION				(PORT_PIN_IN)
#define PORT_PIN31_DIRECTION				(PORT_PIN_IN)

/* Port Pins Direction Change Permission */
#define PORT_PIN00_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN01_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN02_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN03_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN04_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN05_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN06_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN07_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN08_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN09_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN10_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN11_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN12_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN13_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN14_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN15_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN16_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN17_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN18_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN19_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN20_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_LED00_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN22_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN23_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN24_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN25_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_BUTTON00_DIRECTION_CHANGEABLE	(FALSE)
#define PORT_PIN27_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN28_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN29_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN30_DIRECTION_CHANGEABLE		(FALSE)
#define PORT_PIN31_DIRECTION_CHANGEABLE		(FALSE)

/* Port Pins Initial Mode */
#define PORT_INITIAL_PIN00_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN01_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN02_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN03_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN04_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN05_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN06_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN07_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN08_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN09_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN10_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN11_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN12_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN13_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN14_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN15_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN16_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN17_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN18_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN19_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN20_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_LED00_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN22_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN23_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN24_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN25_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_BUTTON00_MODE			(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN27_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN28_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN29_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN30_MODE				(PORT_PIN_MODE_DIO)
#define PORT_INITIAL_PIN31_MODE				(PORT_PIN_MODE_DIO)

/* Port Pins Level Value */
#define PORT_PIN00_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN01_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN02_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN03_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN04_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN05_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN06_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN07_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN08_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN09_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN10_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN11_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN12_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN13_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN14_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN15_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN16_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN17_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN18_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN19_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN20_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_LED00_LEVEL_VALUE					(PORT_PIN_LEVEL_LOW)
#define PORT_PIN22_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN23_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN24_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN25_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_BUTTON00_INTERNAL_PULLUP_DISABLE	(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN27_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN28_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN29_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN30_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)
#define PORT_PIN31_INTERNAL_PULLUP_DISABLE		(INTERNAL_PULLUP_DISABLE)

/* Port Pins Mode */
#define PORT_PIN00_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN01_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN02_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN03_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN04_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN05_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN06_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN07_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN08_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN09_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN10_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN11_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN12_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN13_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN14_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN15_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN16_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN17_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN18_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN19_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN20_MODE						(PORT_PIN_MODE_DIO)
#define PORT_LED00_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN22_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN23_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN24_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN25_MODE						(PORT_PIN_MODE_DIO)
#define PORT_BUTTON00_MODE					(PORT_PIN_MODE_DIO)
#define PORT_PIN27_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN28_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN29_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN30_MODE						(PORT_PIN_MODE_DIO)
#define PORT_PIN31_MODE						(PORT_PIN_MODE_DIO)

/* Port Pins Mode Change Permission */
#define PORT_PIN00_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN01_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN02_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN03_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN04_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN05_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN06_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN07_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN08_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN09_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN10_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN11_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN12_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN13_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN14_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN15_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN16_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN17_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN18_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN19_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN20_Mode_CHANGEABLE			(FALSE)
#define PORT_LED00_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN22_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN23_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN24_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN25_Mode_CHANGEABLE			(FALSE)
#define PORT_BUTTON00_Mode_CHANGEABLE		(FALSE)
#define PORT_PIN27_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN28_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN29_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN30_Mode_CHANGEABLE			(FALSE)
#define PORT_PIN31_Mode_CHANGEABLE			(FALSE)

/* Non AUTOSAR definitions */

#define INTERNAL_PULLUP_RES_SUPPORT				(STD_ON)

#endif /* PORT_CFG_H_ */
