 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.h
 *
 * Description:  This source file contains the Post-Build Configurations for Port
 * 				 Module.
 *
 * Author: Mina Atef
 *
 *******************************************************************************/

/*
 * VENDOR ID		2020
 */
#define PORT_VENDOR_ID								(2020U)

/*
 * MODULE ID		124
 */
#define PORT_MODULE_ID								(124U)

/*
 * Instance ID		0
 */
#define PORT_INSTANCE_ID							(0U)

/*
 * MODULE Version	1.0.0
 */
#define PORT_PB_CFG_SW_MAJOR_VERSION						(1U)
#define PORT_PB_CFG_SW_MINOR_VERSION						(0U)
#define PORT_PB_CFG_SW_PATCH_VERSION						(0U)

/*
 * AUTOSAR RELEASE	4.0.3
 */
#define PORT_PB_CFG_AR_RELEASE_MAJOR_VERSION				(4U)
#define PORT_PB_CFG_AR_RELEASE_MINOR_VERSION				(0U)
#define PORT_PB_CFG_AR_RELEASE_PATCH_VERSION				(3U)

#include"Port.h"

/* Software Version checking between Port PBcfg and Port Modules */
#if((PORT_SW_MAJOR_VERSION != PORT_PB_CFG_SW_MAJOR_VERSION)\
 || (PORT_SW_MINOR_VERSION != PORT_PB_CFG_SW_MINOR_VERSION)\
 || (PORT_SW_PATCH_VERSION != PORT_PB_CFG_SW_PATCH_VERSION))
#error"The SW Version of Port_PBcfg Is not Compatible With SW Version of Port "
#endif

/* AUTOSAR Release checking between Port PBcfg and Port Modules */
#if((PORT_AR_RELEASE_MAJOR_VERSION != PORT_PB_CFG_AR_RELEASE_MAJOR_VERSION)\
 || (PORT_AR_RELEASE_MINOR_VERSION != PORT_PB_CFG_AR_RELEASE_MINOR_VERSION)\
 || (PORT_AR_RELEASE_PATCH_VERSION != PORT_PB_CFG_AR_RELEASE_PATCH_VERSION))
#error"The AR Version of Port_PBcfg Is not Compatible With AR Version of Port "
#endif


/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration =
                                  {
/*Pin 00*/                         {{PORT_PIN00_DIRECTION,  	 PORT_PIN00_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN00_MODE,	   PORT_PIN00_INTERNAL_PULLUP_DISABLE,		 PORT_PIN00_MODE, 		PORT_PIN00_Mode_CHANGEABLE},
/*Pin 01*/							{PORT_PIN01_DIRECTION,   	 PORT_PIN01_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN01_MODE, 	   PORT_PIN01_INTERNAL_PULLUP_DISABLE,		 PORT_PIN01_MODE, 		PORT_PIN01_Mode_CHANGEABLE},
/*Pin 02*/							{PORT_PIN02_DIRECTION,  	 PORT_PIN02_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN02_MODE, 	   PORT_PIN02_INTERNAL_PULLUP_DISABLE,		 PORT_PIN02_MODE, 		PORT_PIN02_Mode_CHANGEABLE},
/*Pin 03*/							{PORT_PIN03_DIRECTION,   	 PORT_PIN03_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN03_MODE, 	   PORT_PIN03_INTERNAL_PULLUP_DISABLE,		 PORT_PIN03_MODE, 		PORT_PIN03_Mode_CHANGEABLE},
/*Pin 04*/							{PORT_PIN04_DIRECTION,       PORT_PIN04_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN04_MODE, 	   PORT_PIN04_INTERNAL_PULLUP_DISABLE,		 PORT_PIN04_MODE, 		PORT_PIN04_Mode_CHANGEABLE},
/*Pin 05*/							{PORT_PIN05_DIRECTION,       PORT_PIN05_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN05_MODE, 	   PORT_PIN05_INTERNAL_PULLUP_DISABLE,		 PORT_PIN05_MODE, 		PORT_PIN05_Mode_CHANGEABLE},
/*Pin 06*/							{PORT_PIN06_DIRECTION,       PORT_PIN06_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN06_MODE, 	   PORT_PIN06_INTERNAL_PULLUP_DISABLE,		 PORT_PIN06_MODE, 		PORT_PIN06_Mode_CHANGEABLE},
/*Pin 07*/							{PORT_PIN07_DIRECTION,       PORT_PIN07_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN07_MODE, 	   PORT_PIN07_INTERNAL_PULLUP_DISABLE,		 PORT_PIN07_MODE, 		PORT_PIN07_Mode_CHANGEABLE},
/*Pin 08*/							{PORT_PIN08_DIRECTION,       PORT_PIN08_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN08_MODE, 	   PORT_PIN08_INTERNAL_PULLUP_DISABLE,		 PORT_PIN08_MODE, 		PORT_PIN08_Mode_CHANGEABLE},
/*Pin 09*/							{PORT_PIN09_DIRECTION,       PORT_PIN09_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN09_MODE, 	   PORT_PIN09_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN09_MODE, 		PORT_PIN09_Mode_CHANGEABLE},
/*Pin 10*/							{PORT_PIN10_DIRECTION,       PORT_PIN10_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN10_MODE, 	   PORT_PIN10_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN10_MODE, 		PORT_PIN10_Mode_CHANGEABLE},
/*Pin 11*/							{PORT_PIN11_DIRECTION,       PORT_PIN11_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN11_MODE,	   PORT_PIN11_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN11_MODE, 		PORT_PIN11_Mode_CHANGEABLE},
/*Pin 12*/							{PORT_PIN12_DIRECTION,       PORT_PIN12_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN12_MODE, 	   PORT_PIN12_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN12_MODE, 		PORT_PIN12_Mode_CHANGEABLE},
/*Pin 13*/							{PORT_PIN13_DIRECTION,       PORT_PIN13_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN13_MODE,   	   PORT_PIN13_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN13_MODE, 		PORT_PIN13_Mode_CHANGEABLE},
/*Pin 14*/							{PORT_PIN14_DIRECTION,       PORT_PIN14_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN14_MODE,	   PORT_PIN14_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN14_MODE, 		PORT_PIN14_Mode_CHANGEABLE},
/*Pin 15*/							{PORT_PIN15_DIRECTION,       PORT_PIN15_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN15_MODE, 	   PORT_PIN15_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN15_MODE, 		PORT_PIN15_Mode_CHANGEABLE},
/*Pin 16*/							{PORT_PIN16_DIRECTION,       PORT_PIN16_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN16_MODE, 	   PORT_PIN16_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN16_MODE, 		PORT_PIN16_Mode_CHANGEABLE},
/*Pin 17*/							{PORT_PIN17_DIRECTION,       PORT_PIN17_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN17_MODE, 	   PORT_PIN17_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN17_MODE, 		PORT_PIN17_Mode_CHANGEABLE},
/*Pin 18*/							{PORT_PIN18_DIRECTION,       PORT_PIN18_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN18_MODE, 	   PORT_PIN18_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN18_MODE, 		PORT_PIN18_Mode_CHANGEABLE},
/*Pin 19*/							{PORT_PIN19_DIRECTION,       PORT_PIN19_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN19_MODE,	   PORT_PIN19_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN19_MODE, 		PORT_PIN19_Mode_CHANGEABLE},
/*Pin 20*/							{PORT_PIN20_DIRECTION,       PORT_PIN20_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN20_MODE,  	   PORT_PIN20_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN20_MODE, 		PORT_PIN20_Mode_CHANGEABLE},
/*LED Pin*/							{PORT_LED00_DIRECTION,       PORT_LED00_DIRECTION_CHANGEABLE, 		PORT_INITIAL_LED00_MODE,   	   PORT_LED00_LEVEL_VALUE, 					 PORT_LED00_MODE, 		PORT_LED00_Mode_CHANGEABLE},
/*Pin 22*/							{PORT_PIN22_DIRECTION,       PORT_PIN22_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN22_MODE,	   PORT_PIN22_INTERNAL_PULLUP_DISABLE,		 PORT_PIN22_MODE, 		PORT_PIN22_Mode_CHANGEABLE},
/*Pin 23*/							{PORT_PIN23_DIRECTION,       PORT_PIN23_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN23_MODE, 	   PORT_PIN23_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN23_MODE, 		PORT_PIN23_Mode_CHANGEABLE},
/*Pin 24*/							{PORT_PIN24_DIRECTION,       PORT_PIN24_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN24_MODE, 	   PORT_PIN24_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN24_MODE, 		PORT_PIN24_Mode_CHANGEABLE},
/*Pin 25*/							{PORT_PIN25_DIRECTION,       PORT_PIN25_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN25_MODE,	   PORT_PIN25_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN25_MODE, 		PORT_PIN25_Mode_CHANGEABLE},
/*Pin 26*/							{PORT_BUTTON00_DIRECTION,    PORT_BUTTON00_DIRECTION_CHANGEABLE,	PORT_INITIAL_BUTTON00_MODE,    PORT_BUTTON00_INTERNAL_PULLUP_DISABLE,	 PORT_BUTTON00_MODE, 	PORT_BUTTON00_Mode_CHANGEABLE},
/*Pin 27*/							{PORT_PIN27_DIRECTION,       PORT_PIN27_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN27_MODE,	   PORT_PIN27_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN27_MODE, 		PORT_PIN27_Mode_CHANGEABLE},
/*Pin 28*/							{PORT_PIN28_DIRECTION,       PORT_PIN28_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN28_MODE, 	   PORT_PIN28_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN28_MODE, 		PORT_PIN28_Mode_CHANGEABLE},
/*Pin 29*/							{PORT_PIN29_DIRECTION,       PORT_PIN29_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN29_MODE, 	   PORT_PIN29_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN29_MODE, 		PORT_PIN29_Mode_CHANGEABLE},
/*Pin 30*/							{PORT_PIN30_DIRECTION,       PORT_PIN30_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN30_MODE,	   PORT_PIN30_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN30_MODE, 		PORT_PIN30_Mode_CHANGEABLE},
/*Pin 31*/							{PORT_PIN31_DIRECTION,       PORT_PIN31_DIRECTION_CHANGEABLE, 		PORT_INITIAL_PIN31_MODE,       PORT_PIN31_INTERNAL_PULLUP_DISABLE, 		 PORT_PIN31_MODE, 		PORT_PIN31_Mode_CHANGEABLE}}
								   };
